### ISSUE TITLE
Active player

### ISSUE THREAD

**Issue by soft2u** [rpuspana/Dice-Battle#1]
When the **PLAYER 2** is active and press "**NEW GAME** button, both players are displayed as active

**Comment by rpuspana** [comment]
Hi soft2u,

Thank you so much for your interest in my game, and thank you for pointing out the bug. 
I can't imagine how that got in there...

Besides this, how do you find the game so far ? I would really appreciate the pros and cons.

Thank you,
Radu

**Comment by soft2u** [comment]
Hello Radu, 
I found this game from your linkedin profile.

**Comment by rpuspana** [comment]
VASI ???

BAI LASA VRAJEALA ! CE FACI ? ZI-MI CUM TI SE PARE ? DE BINE SI DE RAU. BAGA.

MULTAM !

**Comment by rpuspana** [comment]
Fixed ! Thanks.
